use crate::bar::layout::BarEdge;
use crate::bar::state::BatterySnapshot;
use crate::bar::widget::BarRegion;
use relm4::Controller;
use relm4::gtk;
use relm4::gtk::prelude::{OrientableExt, WidgetExt};
use relm4::prelude::*;
use std::sync::Arc;
use wayle_power_profiles::PowerProfilesService;

use super::dropdown::{BatteryDropdown, BatteryDropdownInit, BatteryDropdownInput};
use super::view_model::BatteryViewModel;

// BatteryComponent is the Relm4 model
pub(super) struct BatteryComponent {
    view_model: BatteryViewModel,
    edge: BarEdge,
    region: BarRegion,
    dropdown: Controller<BatteryDropdown>,
}

// BatteryInit carries construction-time dependencies
pub(super) struct BatteryInit {
    pub(super) edge: BarEdge,
    pub(super) region: BarRegion,
    pub(super) power_profiles: Option<Arc<PowerProfilesService>>,
}

// BatteryInput is the component message API
#[derive(Debug)]
pub(super) enum BatteryInput {
    SetPlacement { edge: BarEdge, region: BarRegion },
    SetSnapshot(BatterySnapshot),
    SetUnavailable,
}

// `model` is a special binding generated by the view! macro. It refers
// to the component struct instance, in this case `BatteryComponent`.
#[relm4::component(pub(super))]
impl SimpleComponent for BatteryComponent {
    type Init = BatteryInit;
    type Input = BatteryInput;
    type Output = ();

    view! {
        gtk::MenuButton {
            set_always_show_arrow: false,
            set_cursor_from_name: Some("pointer"),
            add_css_class: "bar-item",
            add_css_class: "battery",
            add_css_class: "flat",

            #[watch]
            set_tooltip_text: model.view_model.tooltip_text.as_deref(),

            #[wrap(Some)]
            #[name = "content"]
            set_child = &gtk::Box {
                #[watch]
                set_orientation: model.edge.orientation(),

                gtk::Image {
                    add_css_class: "battery-icon",

                    #[watch]
                    set_icon_name: Some(model.view_model.icon_name),
                },

                #[name = "percentage"]
                gtk::Label {
                    add_css_class: "battery-percentage",

                    #[watch]
                    set_text: &model.view_model.percentage_text,
                },

                #[name = "energy_rate"]
                gtk::Label {
                    add_css_class: "battery-energy-rate",

                    #[watch]
                    set_text: &model.view_model.energy_rate_text,
                }
            }

        }
    }

    fn init(
        init: Self::Init,
        root: Self::Root,
        _sender: ComponentSender<Self>,
    ) -> ComponentParts<Self> {
        let dropdown = BatteryDropdown::builder()
            .launch(BatteryDropdownInit {
                edge: init.edge,
                region: init.region,
                power_profiles: init.power_profiles.clone(),
            })
            .detach();
        let model = Self {
            view_model: BatteryViewModel::unavailable(),
            edge: init.edge,
            region: init.region,
            dropdown,
        };

        let widgets = view_output!();
        crate::bar::style::add_bar_item_content_classes(&widgets.content, "battery-content");
        crate::bar::style::configure_bar_label(&widgets.percentage);
        crate::bar::style::configure_bar_label(&widgets.energy_rate);

        root.set_popover(Some(model.dropdown.widget()));

        ComponentParts { model, widgets }
    }

    fn update(&mut self, msg: Self::Input, _sender: ComponentSender<Self>) {
        match msg {
            BatteryInput::SetPlacement { edge, region } => {
                self.edge = edge;
                self.region = region;
                self.dropdown
                    .emit(BatteryDropdownInput::SetPlacement { edge, region });
            }
            BatteryInput::SetSnapshot(snapshot) => {
                let view_model = BatteryViewModel::from_snapshot(&snapshot);

                self.dropdown.emit(BatteryDropdownInput::SetSnapshot {
                    view_model: view_model.clone(),
                    active_profile: snapshot.active_profile,
                    available_profiles: snapshot.available_profiles.clone(),
                });

                self.view_model = view_model;
            }
            BatteryInput::SetUnavailable => {
                let view_model = BatteryViewModel::unavailable();
                self.dropdown
                    .emit(BatteryDropdownInput::SetViewModel(view_model.clone()));
                self.view_model = view_model;
            }
        }
    }
}
