use crate::bar::layout::BarEdge;
use crate::bar::state::BatterySnapshot;
use relm4::Controller;
use relm4::gtk;
use relm4::gtk::prelude::{OrientableExt, WidgetExt};
use relm4::prelude::*;
use std::sync::Arc;
use wayle_power_profiles::PowerProfilesService;

use super::dropdown::{BatteryDropdown, BatteryDropdownInput};
use super::view_model::BatteryViewModel;

// BatteryComponent is the Relm4 model
pub(super) struct BatteryComponent {
    view_model: BatteryViewModel,
    snapshot: Option<BatterySnapshot>,
    edge: BarEdge,
    dropdown: Controller<BatteryDropdown>,
}

// BatteryInit carries construction-time dependencies
pub(super) struct BatteryInit {
    pub(super) edge: BarEdge,
    pub(super) power_profiles: Option<Arc<PowerProfilesService>>,
}

// BatteryInput is the component message API
#[derive(Debug)]
pub(super) enum BatteryInput {
    SetEdge(BarEdge),
    SetSnapshot(BatterySnapshot),
    SetUnavailable,
}

// `model` is a special binding generated by the view! macro. It refers
// to the component struct instance, in this case `BatteryComponent`.
#[relm4::component(pub(super))]
impl SimpleComponent for BatteryComponent {
    type Init = BatteryInit;
    type Input = BatteryInput;
    type Output = ();

    view! {
        gtk::MenuButton {
            set_always_show_arrow: false,
            add_css_class: "bar-item",
            add_css_class: "battery",
            add_css_class: "flat",

            #[wrap(Some)]
            set_child = &gtk::Box {
                add_css_class: "bar-item-content",
                add_css_class: "battery-content",

                #[watch]
                set_orientation: model.edge.orientation(),

                gtk::Image {
                    add_css_class: "battery-icon",

                    #[watch]
                    set_icon_name: Some(model.view_model.icon_name),
                },

                gtk::Label {
                    add_css_class: "battery-percentage",

                    #[watch]
                    set_text: &model.view_model.percentage_text,
                },

                gtk::Label {
                    add_css_class: "battery-energy-rate",

                    #[watch]
                    set_text: &model.view_model.energy_rate_text,
                }
            }

        }
    }

    fn init(
        init: Self::Init,
        root: Self::Root,
        _sender: ComponentSender<Self>,
    ) -> ComponentParts<Self> {
        let dropdown = BatteryDropdown::builder()
            .launch(init.power_profiles.clone())
            .detach();
        let model = Self {
            view_model: BatteryViewModel::unavailable(),
            snapshot: None,
            edge: init.edge,
            dropdown,
        };

        let widgets = view_output!();

        root.set_popover(Some(model.dropdown.widget()));

        ComponentParts { model, widgets }
    }

    fn update(&mut self, msg: Self::Input, _sender: ComponentSender<Self>) {
        match msg {
            BatteryInput::SetEdge(edge) => {
                self.edge = edge;
            }
            BatteryInput::SetSnapshot(snapshot) => {
                let view_model = BatteryViewModel::from_snapshot(&snapshot);

                self.dropdown
                    .emit(BatteryDropdownInput::SetSnapshot {
                        view_model: view_model.clone(),
                        active_profile: snapshot.active_profile,
                        available_profiles: snapshot.available_profiles.clone(),
                    });

                self.view_model = view_model;
                self.snapshot = Some(snapshot);
            }
            BatteryInput::SetUnavailable => {
                let view_model = BatteryViewModel::unavailable();
                self.dropdown
                    .emit(BatteryDropdownInput::SetViewModel(view_model.clone()));
                self.view_model = view_model;
                self.snapshot = None;
            }
        }
    }
}