use super::{CssValueKind, SettingUiSpec, StyleSettingSpec};

pub(super) fn style_settings() -> impl Iterator<Item = &'static StyleSettingSpec> {
    PALETTE_STYLE_SETTINGS
        .iter()
        .chain(BAR_STYLE_SETTINGS.iter())
        .chain(DETAIL_STYLE_SETTINGS.iter())
}

const PALETTE_STYLE_SETTINGS: &[StyleSettingSpec] = &[
    StyleSettingSpec {
        section: "Palette",
        group: "palette",
        key: "primary",
        path: &["style", "palette", "primary"],
        setting: Some(SettingUiSpec::Color {
            label: "Primary",
            default: "#89b4fa",
        }),
        variable: "--md-sys-color-primary",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Palette",
        group: "palette",
        key: "on-primary",
        path: &["style", "palette", "on-primary"],
        setting: Some(SettingUiSpec::Color {
            label: "On primary",
            default: "#1e1e2e",
        }),
        variable: "--md-sys-color-on-primary",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Palette",
        group: "palette",
        key: "primary-container",
        path: &["style", "palette", "primary-container"],
        setting: Some(SettingUiSpec::Color {
            label: "Primary container",
            default: "rgba(137, 180, 250, 0.22)",
        }),
        variable: "--md-sys-color-primary-container",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Palette",
        group: "palette",
        key: "on-primary-container",
        path: &["style", "palette", "on-primary-container"],
        setting: Some(SettingUiSpec::Color {
            label: "On primary container",
            default: "#f1f3f4",
        }),
        variable: "--md-sys-color-on-primary-container",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Palette",
        group: "palette",
        key: "secondary",
        path: &["style", "palette", "secondary"],
        setting: Some(SettingUiSpec::Color {
            label: "Secondary",
            default: "#cba6f7",
        }),
        variable: "--md-sys-color-secondary",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Palette",
        group: "palette",
        key: "on-secondary",
        path: &["style", "palette", "on-secondary"],
        setting: Some(SettingUiSpec::Color {
            label: "On secondary",
            default: "#1e1e2e",
        }),
        variable: "--md-sys-color-on-secondary",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Palette",
        group: "palette",
        key: "secondary-container",
        path: &["style", "palette", "secondary-container"],
        setting: Some(SettingUiSpec::Color {
            label: "Secondary container",
            default: "rgba(203, 166, 247, 0.18)",
        }),
        variable: "--md-sys-color-secondary-container",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Palette",
        group: "palette",
        key: "on-secondary-container",
        path: &["style", "palette", "on-secondary-container"],
        setting: Some(SettingUiSpec::Color {
            label: "On secondary container",
            default: "#f1f3f4",
        }),
        variable: "--md-sys-color-on-secondary-container",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Palette",
        group: "palette",
        key: "tertiary",
        path: &["style", "palette", "tertiary"],
        setting: Some(SettingUiSpec::Color {
            label: "Tertiary",
            default: "#fdd664",
        }),
        variable: "--md-sys-color-tertiary",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Palette",
        group: "palette",
        key: "on-tertiary",
        path: &["style", "palette", "on-tertiary"],
        setting: Some(SettingUiSpec::Color {
            label: "On tertiary",
            default: "#1e1e2e",
        }),
        variable: "--md-sys-color-on-tertiary",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Palette",
        group: "palette",
        key: "tertiary-container",
        path: &["style", "palette", "tertiary-container"],
        setting: Some(SettingUiSpec::Color {
            label: "Tertiary container",
            default: "rgba(253, 214, 100, 0.18)",
        }),
        variable: "--md-sys-color-tertiary-container",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Palette",
        group: "palette",
        key: "on-tertiary-container",
        path: &["style", "palette", "on-tertiary-container"],
        setting: Some(SettingUiSpec::Color {
            label: "On tertiary container",
            default: "#f1f3f4",
        }),
        variable: "--md-sys-color-on-tertiary-container",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Palette",
        group: "palette",
        key: "surface",
        path: &["style", "palette", "surface"],
        setting: Some(SettingUiSpec::Color {
            label: "Surface",
            default: "rgba(30, 30, 46, 1)",
        }),
        variable: "--md-sys-color-surface",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Palette",
        group: "palette",
        key: "on-surface",
        path: &["style", "palette", "on-surface"],
        setting: Some(SettingUiSpec::Color {
            label: "On surface",
            default: "#f1f3f4",
        }),
        variable: "--md-sys-color-on-surface",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Palette",
        group: "palette",
        key: "on-surface-variant",
        path: &["style", "palette", "on-surface-variant"],
        setting: Some(SettingUiSpec::Color {
            label: "On surface variant",
            default: "rgba(241, 243, 244, 0.72)",
        }),
        variable: "--md-sys-color-on-surface-variant",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Palette",
        group: "palette",
        key: "surface-container-lowest",
        path: &["style", "palette", "surface-container-lowest"],
        setting: Some(SettingUiSpec::Color {
            label: "Surface container lowest",
            default: "rgba(30, 30, 46, 0.96)",
        }),
        variable: "--md-sys-color-surface-container-lowest",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Palette",
        group: "palette",
        key: "surface-container-low",
        path: &["style", "palette", "surface-container-low"],
        setting: Some(SettingUiSpec::Color {
            label: "Surface container low",
            default: "rgba(241, 243, 244, 0.045)",
        }),
        variable: "--md-sys-color-surface-container-low",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Palette",
        group: "palette",
        key: "surface-container",
        path: &["style", "palette", "surface-container"],
        setting: Some(SettingUiSpec::Color {
            label: "Surface container",
            default: "rgba(241, 243, 244, 0.06)",
        }),
        variable: "--md-sys-color-surface-container",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Palette",
        group: "palette",
        key: "surface-container-high",
        path: &["style", "palette", "surface-container-high"],
        setting: Some(SettingUiSpec::Color {
            label: "Surface container high",
            default: "rgba(241, 243, 244, 0.08)",
        }),
        variable: "--md-sys-color-surface-container-high",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Palette",
        group: "palette",
        key: "surface-container-highest",
        path: &["style", "palette", "surface-container-highest"],
        setting: Some(SettingUiSpec::Color {
            label: "Surface container highest",
            default: "rgba(241, 243, 244, 0.12)",
        }),
        variable: "--md-sys-color-surface-container-highest",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Palette",
        group: "palette",
        key: "outline",
        path: &["style", "palette", "outline"],
        setting: Some(SettingUiSpec::Color {
            label: "Outline",
            default: "rgba(241, 243, 244, 0.14)",
        }),
        variable: "--md-sys-color-outline",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Palette",
        group: "palette",
        key: "outline-variant",
        path: &["style", "palette", "outline-variant"],
        setting: Some(SettingUiSpec::Color {
            label: "Outline variant",
            default: "rgba(241, 243, 244, 0.08)",
        }),
        variable: "--md-sys-color-outline-variant",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Palette",
        group: "palette",
        key: "error",
        path: &["style", "palette", "error"],
        setting: Some(SettingUiSpec::Color {
            label: "Error",
            default: "#f28b82",
        }),
        variable: "--md-sys-color-error",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Palette",
        group: "palette",
        key: "on-error",
        path: &["style", "palette", "on-error"],
        setting: Some(SettingUiSpec::Color {
            label: "On error",
            default: "#1e1e2e",
        }),
        variable: "--md-sys-color-on-error",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Palette",
        group: "palette",
        key: "error-container",
        path: &["style", "palette", "error-container"],
        setting: Some(SettingUiSpec::Color {
            label: "Error container",
            default: "rgba(242, 139, 130, 0.18)",
        }),
        variable: "--md-sys-color-error-container",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Palette",
        group: "palette",
        key: "on-error-container",
        path: &["style", "palette", "on-error-container"],
        setting: Some(SettingUiSpec::Color {
            label: "On error container",
            default: "#f1f3f4",
        }),
        variable: "--md-sys-color-on-error-container",
        css_kind: CssValueKind::String { quoted: false },
    },
];

const BAR_STYLE_SETTINGS: &[StyleSettingSpec] = &[
    StyleSettingSpec {
        section: "Bar",
        group: "bar",
        key: "background-color",
        path: &["style", "bar", "background-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Background color",
            default: "rgba(30, 30, 46, 0.7)",
        }),
        variable: "--bar-background-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Bar",
        group: "bar",
        key: "color",
        path: &["style", "bar", "color"],
        setting: Some(SettingUiSpec::Color {
            label: "Text color",
            default: "#f1f3f4",
        }),
        variable: "--bar-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Bar",
        group: "bar",
        key: "font-family",
        path: &["style", "bar", "font-family"],
        setting: Some(SettingUiSpec::String {
            label: "Font family",
            default: "Adwaita Sans",
        }),
        variable: "--bar-font-family",
        css_kind: CssValueKind::String { quoted: true },
    },
    StyleSettingSpec {
        section: "Bar",
        group: "bar",
        key: "font-size",
        path: &["style", "bar", "font-size"],
        setting: Some(SettingUiSpec::Number {
            label: "Font size",
            default: 12,
            min: 8.0,
            max: 24.0,
            step: 1.0,
        }),
        variable: "--bar-font-size",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
    StyleSettingSpec {
        section: "Bar",
        group: "bar",
        key: "font-weight",
        path: &["style", "bar", "font-weight"],
        setting: Some(SettingUiSpec::Number {
            label: "Font weight",
            default: 100,
            min: 100.0,
            max: 900.0,
            step: 50.0,
        }),
        variable: "--bar-font-weight",
        css_kind: CssValueKind::Integer { unit: "" },
    },
    StyleSettingSpec {
        section: "Bar",
        group: "bar",
        key: "size",
        path: &["style", "bar", "size"],
        setting: Some(SettingUiSpec::Number {
            label: "Size",
            default: 24,
            min: 12.0,
            max: 80.0,
            step: 1.0,
        }),
        variable: "--bar-size",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
    StyleSettingSpec {
        section: "Bar",
        group: "bar",
        key: "padding-x",
        path: &["style", "bar", "padding-x"],
        setting: Some(SettingUiSpec::Number {
            label: "Horizontal padding",
            default: 0,
            min: 0.0,
            max: 24.0,
            step: 1.0,
        }),
        variable: "--bar-padding-x",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
    StyleSettingSpec {
        section: "Bar",
        group: "bar",
        key: "padding-y",
        path: &["style", "bar", "padding-y"],
        setting: Some(SettingUiSpec::Number {
            label: "Vertical padding",
            default: 0,
            min: 0.0,
            max: 24.0,
            step: 1.0,
        }),
        variable: "--bar-padding-y",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
    StyleSettingSpec {
        section: "Bar",
        group: "bar",
        key: "widget-gap",
        path: &["style", "bar", "widget-gap"],
        setting: Some(SettingUiSpec::Number {
            label: "Widget gap",
            default: 4,
            min: 0.0,
            max: 24.0,
            step: 1.0,
        }),
        variable: "--bar-widget-gap",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
    StyleSettingSpec {
        section: "Bar",
        group: "bar",
        key: "widget-thickness",
        path: &["style", "bar", "widget-thickness"],
        setting: Some(SettingUiSpec::Number {
            label: "Widget thickness",
            default: 16,
            min: 8.0,
            max: 80.0,
            step: 1.0,
        }),
        variable: "--bar-widget-thickness",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
    StyleSettingSpec {
        section: "Bar",
        group: "bar",
        key: "widget-background-color",
        path: &["style", "bar", "widget-background-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Widget background",
            default: "transparent",
        }),
        variable: "--bar-widget-background-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Bar",
        group: "bar",
        key: "widget-border-color",
        path: &["style", "bar", "widget-border-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Widget border color",
            default: "transparent",
        }),
        variable: "--bar-widget-border-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Bar",
        group: "bar",
        key: "widget-border-width",
        path: &["style", "bar", "widget-border-width"],
        setting: Some(SettingUiSpec::Number {
            label: "Widget border width",
            default: 0,
            min: 0.0,
            max: 8.0,
            step: 1.0,
        }),
        variable: "--bar-widget-border-width",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
    StyleSettingSpec {
        section: "Bar",
        group: "bar",
        key: "widget-border-radius",
        path: &["style", "bar", "widget-border-radius"],
        setting: Some(SettingUiSpec::Number {
            label: "Widget border radius",
            default: 0,
            min: 0.0,
            max: 24.0,
            step: 1.0,
        }),
        variable: "--bar-widget-border-radius",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
    StyleSettingSpec {
        section: "Bar",
        group: "bar",
        key: "widget-padding-x",
        path: &["style", "bar", "widget-padding-x"],
        setting: Some(SettingUiSpec::Number {
            label: "Widget horizontal padding",
            default: 4,
            min: 0.0,
            max: 24.0,
            step: 1.0,
        }),
        variable: "--bar-widget-padding-x",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
    StyleSettingSpec {
        section: "Bar",
        group: "bar",
        key: "widget-padding-y",
        path: &["style", "bar", "widget-padding-y"],
        setting: Some(SettingUiSpec::Number {
            label: "Widget vertical padding",
            default: 0,
            min: 0.0,
            max: 24.0,
            step: 1.0,
        }),
        variable: "--bar-widget-padding-y",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
    StyleSettingSpec {
        section: "Bar",
        group: "bar",
        key: "widget-margin-x",
        path: &["style", "bar", "widget-margin-x"],
        setting: Some(SettingUiSpec::Number {
            label: "Widget horizontal margin",
            default: 0,
            min: 0.0,
            max: 24.0,
            step: 1.0,
        }),
        variable: "--bar-widget-margin-x",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
    StyleSettingSpec {
        section: "Bar",
        group: "bar",
        key: "widget-margin-y",
        path: &["style", "bar", "widget-margin-y"],
        setting: Some(SettingUiSpec::Number {
            label: "Widget vertical margin",
            default: 0,
            min: 0.0,
            max: 24.0,
            step: 1.0,
        }),
        variable: "--bar-widget-margin-y",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
    StyleSettingSpec {
        section: "Bar",
        group: "bar",
        key: "region-border-radius",
        path: &["style", "bar", "region-border-radius"],
        setting: Some(SettingUiSpec::Number {
            label: "Region border radius",
            default: 6,
            min: 0.0,
            max: 24.0,
            step: 1.0,
        }),
        variable: "--bar-region-border-radius",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
];

const DETAIL_STYLE_SETTINGS: &[StyleSettingSpec] = &[
    StyleSettingSpec {
        section: "Workspaces",
        group: "workspaces",
        key: "widget-background-color",
        path: &["style", "workspaces", "widget-background-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Widget background",
            default: "rgba(255, 255, 255, 0.1)",
        }),
        variable: "--workspaces-widget-background-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Workspaces",
        group: "workspaces",
        key: "content-border-radius",
        path: &["style", "workspaces", "content-border-radius"],
        setting: Some(SettingUiSpec::Number {
            label: "Content border radius",
            default: 6,
            min: 0.0,
            max: 24.0,
            step: 1.0,
        }),
        variable: "--workspaces-content-border-radius",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
    StyleSettingSpec {
        section: "Workspaces",
        group: "workspaces",
        key: "widget-border-color",
        path: &["style", "workspaces", "widget-border-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Widget border color",
            default: "transparent",
        }),
        variable: "--workspaces-widget-border-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Workspaces",
        group: "workspaces",
        key: "widget-border-width",
        path: &["style", "workspaces", "widget-border-width"],
        setting: Some(SettingUiSpec::Number {
            label: "Widget border width",
            default: 0,
            min: 0.0,
            max: 8.0,
            step: 1.0,
        }),
        variable: "--workspaces-widget-border-width",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
    StyleSettingSpec {
        section: "Workspaces",
        group: "workspaces",
        key: "content-padding",
        path: &["style", "workspaces", "content-padding"],
        setting: Some(SettingUiSpec::Number {
            label: "Content padding",
            default: 4,
            min: 0.0,
            max: 20.0,
            step: 1.0,
        }),
        variable: "--workspaces-content-padding",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
    StyleSettingSpec {
        section: "Workspaces",
        group: "workspaces",
        key: "workspace-border-radius",
        path: &["style", "workspaces", "workspace-border-radius"],
        setting: Some(SettingUiSpec::Number {
            label: "Workspace border radius",
            default: 6,
            min: 0.0,
            max: 24.0,
            step: 1.0,
        }),
        variable: "--workspace-border-radius",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
    StyleSettingSpec {
        section: "Workspaces",
        group: "workspaces",
        key: "active-color",
        path: &["style", "workspaces", "active-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Active color",
            default: "#f1f3f4",
        }),
        variable: "--workspace-active-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Workspaces",
        group: "workspaces",
        key: "focused-color",
        path: &["style", "workspaces", "focused-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Focused color",
            default: "#89b4fa",
        }),
        variable: "--workspace-focused-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Workspaces",
        group: "workspaces",
        key: "urgent-color",
        path: &["style", "workspaces", "urgent-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Urgent color",
            default: "#f28b82",
        }),
        variable: "--workspace-urgent-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Workspaces",
        group: "workspaces",
        key: "indicator-background-color",
        path: &["style", "workspaces", "indicator-background-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Indicator background",
            default: "rgba(137, 180, 250, 0.5)",
        }),
        variable: "--workspace-indicator-background-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Workspaces",
        group: "workspaces",
        key: "indicator-border-radius",
        path: &["style", "workspaces", "indicator-border-radius"],
        setting: Some(SettingUiSpec::Number {
            label: "Indicator border radius",
            default: 6,
            min: 0.0,
            max: 24.0,
            step: 1.0,
        }),
        variable: "--workspace-indicator-border-radius",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
    StyleSettingSpec {
        section: "Workspaces",
        group: "workspaces",
        key: "status-color",
        path: &["style", "workspaces", "status-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Status color",
            default: "#fdd664",
        }),
        variable: "--workspace-status-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Floating surfaces",
        group: "surfaces",
        key: "background-color",
        path: &["style", "surfaces", "background-color"],
        setting: None,
        variable: "--surface-background-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Floating surfaces",
        group: "surfaces",
        key: "border-color",
        path: &["style", "surfaces", "border-color"],
        setting: None,
        variable: "--surface-border-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Floating surfaces",
        group: "surfaces",
        key: "border-radius",
        path: &["style", "surfaces", "border-radius"],
        setting: None,
        variable: "--surface-border-radius",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
    StyleSettingSpec {
        section: "Floating surfaces",
        group: "surfaces",
        key: "color",
        path: &["style", "surfaces", "color"],
        setting: None,
        variable: "--surface-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Floating surfaces",
        group: "surfaces",
        key: "shadow",
        path: &["style", "surfaces", "shadow"],
        setting: None,
        variable: "--surface-shadow",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Dropdowns",
        group: "dropdowns",
        key: "font-family",
        path: &["style", "dropdowns", "font-family"],
        setting: None,
        variable: "--dropdown-font-family",
        css_kind: CssValueKind::String { quoted: true },
    },
    StyleSettingSpec {
        section: "Dropdowns",
        group: "dropdowns",
        key: "font-size",
        path: &["style", "dropdowns", "font-size"],
        setting: None,
        variable: "--dropdown-font-size",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
    StyleSettingSpec {
        section: "Dropdowns",
        group: "dropdowns",
        key: "font-weight",
        path: &["style", "dropdowns", "font-weight"],
        setting: None,
        variable: "--dropdown-font-weight",
        css_kind: CssValueKind::Integer { unit: "" },
    },
    StyleSettingSpec {
        section: "Dropdowns",
        group: "dropdowns",
        key: "content-padding",
        path: &["style", "dropdowns", "content-padding"],
        setting: None,
        variable: "--dropdown-content-padding",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Battery",
        group: "battery",
        key: "meter-fill-color",
        path: &["style", "battery", "meter-fill-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Meter fill color",
            default: "rgba(137, 180, 250, 0.72)",
        }),
        variable: "--battery-meter-fill-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Battery",
        group: "battery",
        key: "detail-background-color",
        path: &["style", "battery", "detail-background-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Detail background",
            default: "rgba(241, 243, 244, 0.06)",
        }),
        variable: "--battery-detail-background-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Battery",
        group: "battery",
        key: "detail-border-color",
        path: &["style", "battery", "detail-border-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Detail border",
            default: "rgba(241, 243, 244, 0.08)",
        }),
        variable: "--battery-detail-border-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Battery",
        group: "battery",
        key: "profile-border-color",
        path: &["style", "battery", "profile-border-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Profile border",
            default: "rgba(241, 243, 244, 0.16)",
        }),
        variable: "--battery-profile-border-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Battery",
        group: "battery",
        key: "profile-hover-background-color",
        path: &["style", "battery", "profile-hover-background-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Profile hover background",
            default: "rgba(241, 243, 244, 0.08)",
        }),
        variable: "--battery-profile-hover-background-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Battery",
        group: "battery",
        key: "profile-hover-border-color",
        path: &["style", "battery", "profile-hover-border-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Profile hover border",
            default: "rgba(137, 180, 250, 0.45)",
        }),
        variable: "--battery-profile-hover-border-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Battery",
        group: "battery",
        key: "profile-active-background-color",
        path: &["style", "battery", "profile-active-background-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Profile active background",
            default: "rgba(137, 180, 250, 0.22)",
        }),
        variable: "--battery-profile-active-background-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Battery",
        group: "battery",
        key: "profile-active-border-color",
        path: &["style", "battery", "profile-active-border-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Profile active border",
            default: "rgba(137, 180, 250, 0.75)",
        }),
        variable: "--battery-profile-active-border-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Systray",
        group: "systray",
        key: "widget-background-color",
        path: &["style", "systray", "widget-background-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Widget background",
            default: "rgba(255, 255, 255, 0.1)",
        }),
        variable: "--systray-widget-background-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Systray",
        group: "systray",
        key: "content-border-radius",
        path: &["style", "systray", "content-border-radius"],
        setting: Some(SettingUiSpec::Number {
            label: "Content border radius",
            default: 12,
            min: 0.0,
            max: 32.0,
            step: 1.0,
        }),
        variable: "--systray-content-border-radius",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
    StyleSettingSpec {
        section: "Systray",
        group: "systray",
        key: "widget-border-color",
        path: &["style", "systray", "widget-border-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Widget border color",
            default: "transparent",
        }),
        variable: "--systray-widget-border-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Systray",
        group: "systray",
        key: "widget-border-width",
        path: &["style", "systray", "widget-border-width"],
        setting: Some(SettingUiSpec::Number {
            label: "Widget border width",
            default: 0,
            min: 0.0,
            max: 8.0,
            step: 1.0,
        }),
        variable: "--systray-widget-border-width",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
    StyleSettingSpec {
        section: "Systray",
        group: "systray",
        key: "content-padding-x",
        path: &["style", "systray", "content-padding-x"],
        setting: Some(SettingUiSpec::Number {
            label: "Content horizontal padding",
            default: 8,
            min: 0.0,
            max: 24.0,
            step: 1.0,
        }),
        variable: "--systray-content-padding-x",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
    StyleSettingSpec {
        section: "Systray",
        group: "systray",
        key: "menu-hover-background-color",
        path: &["style", "systray", "menu-hover-background-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Menu hover background",
            default: "rgba(241, 243, 244, 0.08)",
        }),
        variable: "--systray-menu-hover-background-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "OSD",
        group: "osd",
        key: "font-family",
        path: &["style", "osd", "font-family"],
        setting: Some(SettingUiSpec::String {
            label: "Font family",
            default: "Adwaita Sans",
        }),
        variable: "--osd-font-family",
        css_kind: CssValueKind::String { quoted: true },
    },
    StyleSettingSpec {
        section: "OSD",
        group: "osd",
        key: "font-size",
        path: &["style", "osd", "font-size"],
        setting: Some(SettingUiSpec::Number {
            label: "Font size",
            default: 14,
            min: 8.0,
            max: 32.0,
            step: 1.0,
        }),
        variable: "--osd-font-size",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
    StyleSettingSpec {
        section: "OSD",
        group: "osd",
        key: "font-weight",
        path: &["style", "osd", "font-weight"],
        setting: Some(SettingUiSpec::Number {
            label: "Font weight",
            default: 500,
            min: 100.0,
            max: 900.0,
            step: 50.0,
        }),
        variable: "--osd-font-weight",
        css_kind: CssValueKind::Integer { unit: "" },
    },
    StyleSettingSpec {
        section: "OSD",
        group: "osd",
        key: "level-track-color",
        path: &["style", "osd", "level-track-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Level track override",
            default: "rgba(241, 243, 244, 0.16)",
        }),
        variable: "--osd-level-track-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "OSD",
        group: "osd",
        key: "level-fill-color",
        path: &["style", "osd", "level-fill-color"],
        setting: None,
        variable: "--osd-level-fill-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "OSD",
        group: "osd",
        key: "brightness-level-fill-color",
        path: &["style", "osd", "brightness-level-fill-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Brightness fill override",
            default: "#fdd664",
        }),
        variable: "--osd-brightness-level-fill-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "OSD",
        group: "osd",
        key: "volume-level-fill-color",
        path: &["style", "osd", "volume-level-fill-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Volume fill override",
            default: "#89b4fa",
        }),
        variable: "--osd-volume-level-fill-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "OSD",
        group: "osd",
        key: "muted-level-fill-color",
        path: &["style", "osd", "muted-level-fill-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Muted fill override",
            default: "#f28b82",
        }),
        variable: "--osd-muted-level-fill-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Notification cards",
        group: "notifications",
        key: "font-family",
        path: &["style", "notifications", "font-family"],
        setting: Some(SettingUiSpec::String {
            label: "Font family",
            default: "Adwaita Sans",
        }),
        variable: "--notification-font-family",
        css_kind: CssValueKind::String { quoted: true },
    },
    StyleSettingSpec {
        section: "Notification cards",
        group: "notifications",
        key: "window-font-size",
        path: &["style", "notifications", "window-font-size"],
        setting: Some(SettingUiSpec::Number {
            label: "Window font size",
            default: 12,
            min: 8.0,
            max: 24.0,
            step: 1.0,
        }),
        variable: "--notification-window-font-size",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
    StyleSettingSpec {
        section: "Notification cards",
        group: "notifications",
        key: "window-font-weight",
        path: &["style", "notifications", "window-font-weight"],
        setting: Some(SettingUiSpec::Number {
            label: "Window font weight",
            default: 100,
            min: 100.0,
            max: 900.0,
            step: 50.0,
        }),
        variable: "--notification-window-font-weight",
        css_kind: CssValueKind::Integer { unit: "" },
    },
    StyleSettingSpec {
        section: "Notification cards",
        group: "notifications",
        key: "body-font-weight",
        path: &["style", "notifications", "body-font-weight"],
        setting: Some(SettingUiSpec::Number {
            label: "Body font weight",
            default: 400,
            min: 100.0,
            max: 900.0,
            step: 50.0,
        }),
        variable: "--notification-body-font-weight",
        css_kind: CssValueKind::Integer { unit: "" },
    },
    StyleSettingSpec {
        section: "Notification cards",
        group: "notifications",
        key: "indicator-border-width",
        path: &["style", "notifications", "indicator-border-width"],
        setting: Some(SettingUiSpec::Number {
            label: "Indicator border width",
            default: 4,
            min: 0.0,
            max: 8.0,
            step: 1.0,
        }),
        variable: "--notification-indicator-border-width",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
    StyleSettingSpec {
        section: "Notification cards",
        group: "notifications",
        key: "list-icon-size",
        path: &["style", "notifications", "list-icon-size"],
        setting: Some(SettingUiSpec::Number {
            label: "List icon size",
            default: 30,
            min: 16.0,
            max: 64.0,
            step: 1.0,
        }),
        variable: "--notification-list-icon-size",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
    StyleSettingSpec {
        section: "Notification cards",
        group: "notifications",
        key: "hide-scrollbar",
        path: &["style", "notifications", "hide-scrollbar"],
        setting: Some(SettingUiSpec::Toggle {
            label: "Hide scrollbar",
            default: true,
        }),
        variable: "--notification-scrollbar-opacity",
        css_kind: CssValueKind::Bool {
            true_value: "0",
            false_value: "1",
        },
    },
    StyleSettingSpec {
        section: "Notification cards",
        group: "notifications",
        key: "row-background-color",
        path: &["style", "notifications", "row-background-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Row background",
            default: "rgba(241, 243, 244, 0.055)",
        }),
        variable: "--notification-row-background-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Notification cards",
        group: "notifications",
        key: "row-hover-background-color",
        path: &["style", "notifications", "row-hover-background-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Row hover background",
            default: "rgba(241, 243, 244, 0.085)",
        }),
        variable: "--notification-row-hover-background-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Notification cards",
        group: "notifications",
        key: "row-border-color",
        path: &["style", "notifications", "row-border-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Row border",
            default: "rgba(241, 243, 244, 0.12)",
        }),
        variable: "--notification-row-border-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Notification cards",
        group: "notifications",
        key: "row-hover-border-color",
        path: &["style", "notifications", "row-hover-border-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Row hover border",
            default: "rgba(241, 243, 244, 0.18)",
        }),
        variable: "--notification-row-hover-border-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Notification cards",
        group: "notifications",
        key: "row-low-border-color",
        path: &["style", "notifications", "row-low-border-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Low urgency border",
            default: "rgba(241, 243, 244, 0.28)",
        }),
        variable: "--notification-row-low-border-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Notification cards",
        group: "notifications",
        key: "row-normal-border-color",
        path: &["style", "notifications", "row-normal-border-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Normal urgency border",
            default: "rgba(137, 180, 250, 0.8)",
        }),
        variable: "--notification-row-normal-border-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Notification cards",
        group: "notifications",
        key: "row-critical-border-color",
        path: &["style", "notifications", "row-critical-border-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Critical urgency border",
            default: "rgba(242, 139, 130, 0.9)",
        }),
        variable: "--notification-row-critical-border-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Notification cards",
        group: "notifications",
        key: "toast-border-color",
        path: &["style", "notifications", "toast-border-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Toast border",
            default: "rgba(241, 243, 244, 0.28)",
        }),
        variable: "--notification-toast-border-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Notification cards",
        group: "notifications",
        key: "list-action-border-color",
        path: &["style", "notifications", "list-action-border-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Action border",
            default: "rgba(241, 243, 244, 0.16)",
        }),
        variable: "--notification-list-action-border-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Notification cards",
        group: "notifications",
        key: "action-border-color",
        path: &["style", "notifications", "action-border-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Toast action border",
            default: "rgba(241, 243, 244, 0.18)",
        }),
        variable: "--notification-action-border-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Notification cards",
        group: "notifications",
        key: "clear-all-border-color",
        path: &["style", "notifications", "clear-all-border-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Clear all border",
            default: "rgba(241, 243, 244, 0.14)",
        }),
        variable: "--notification-clear-all-border-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Notification cards",
        group: "notifications",
        key: "clear-all-hover-border-color",
        path: &["style", "notifications", "clear-all-hover-border-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Clear all hover border",
            default: "rgba(242, 139, 130, 0.55)",
        }),
        variable: "--notification-clear-all-hover-border-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Notification cards",
        group: "notifications",
        key: "list-action-hover-background-color",
        path: &[
            "style",
            "notifications",
            "list-action-hover-background-color",
        ],
        setting: Some(SettingUiSpec::Color {
            label: "Action hover background",
            default: "rgba(241, 243, 244, 0.08)",
        }),
        variable: "--notification-list-action-hover-background-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Notification cards",
        group: "notifications",
        key: "list-action-hover-border-color",
        path: &["style", "notifications", "list-action-hover-border-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Action hover border",
            default: "rgba(137, 180, 250, 0.65)",
        }),
        variable: "--notification-list-action-hover-border-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Notification cards",
        group: "notifications",
        key: "toast-critical-border-color",
        path: &["style", "notifications", "toast-critical-border-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Critical toast border",
            default: "rgba(242, 139, 130, 0.85)",
        }),
        variable: "--notification-toast-critical-border-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Action menu",
        group: "action-menu",
        key: "button-border-color",
        path: &["style", "action-menu", "button-border-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Button border",
            default: "rgba(241, 243, 244, 0.14)",
        }),
        variable: "--action-menu-button-border-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Action menu",
        group: "action-menu",
        key: "button-hover-background-color",
        path: &["style", "action-menu", "button-hover-background-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Button hover background",
            default: "rgba(241, 243, 244, 0.08)",
        }),
        variable: "--action-menu-button-hover-background-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Action menu",
        group: "action-menu",
        key: "button-hover-border-color",
        path: &["style", "action-menu", "button-hover-border-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Button hover border",
            default: "rgba(137, 180, 250, 0.65)",
        }),
        variable: "--action-menu-button-hover-border-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Action menu",
        group: "action-menu",
        key: "icon-font-family",
        path: &["style", "action-menu", "icon-font-family"],
        setting: Some(SettingUiSpec::String {
            label: "Icon font family",
            default: "Symbols Nerd Font",
        }),
        variable: "--action-menu-icon-font-family",
        css_kind: CssValueKind::String { quoted: true },
    },
    StyleSettingSpec {
        section: "Action menu",
        group: "action-menu",
        key: "icon-font-size",
        path: &["style", "action-menu", "icon-font-size"],
        setting: Some(SettingUiSpec::String {
            label: "Icon font size",
            default: "1.65em",
        }),
        variable: "--action-menu-icon-font-size",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Settings window",
        group: "settings",
        key: "background-color",
        path: &["style", "settings", "background-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Background color",
            default: "rgba(20, 20, 24, 0.96)",
        }),
        variable: "--settings-background-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Settings window",
        group: "settings",
        key: "color",
        path: &["style", "settings", "color"],
        setting: Some(SettingUiSpec::Color {
            label: "Text color",
            default: "rgba(245, 245, 245, 0.95)",
        }),
        variable: "--settings-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Settings window",
        group: "settings",
        key: "font-family",
        path: &["style", "settings", "font-family"],
        setting: Some(SettingUiSpec::String {
            label: "Font family",
            default: "Adwaita Sans",
        }),
        variable: "--settings-font-family",
        css_kind: CssValueKind::String { quoted: true },
    },
    StyleSettingSpec {
        section: "Settings window",
        group: "settings",
        key: "font-size",
        path: &["style", "settings", "font-size"],
        setting: Some(SettingUiSpec::Number {
            label: "Font size",
            default: 14,
            min: 8.0,
            max: 24.0,
            step: 1.0,
        }),
        variable: "--settings-font-size",
        css_kind: CssValueKind::Integer { unit: "px" },
    },
    StyleSettingSpec {
        section: "Settings window",
        group: "settings",
        key: "sidebar-background-color",
        path: &["style", "settings", "sidebar-background-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Sidebar background",
            default: "rgba(255, 255, 255, 0.06)",
        }),
        variable: "--settings-sidebar-background-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Settings window",
        group: "settings",
        key: "sidebar-active-background-color",
        path: &["style", "settings", "sidebar-active-background-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Sidebar active background",
            default: "rgba(255, 255, 255, 0.12)",
        }),
        variable: "--settings-sidebar-active-background-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Settings window",
        group: "settings",
        key: "group-background-color",
        path: &["style", "settings", "group-background-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Group background",
            default: "rgba(255, 255, 255, 0.07)",
        }),
        variable: "--settings-group-background-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Settings window",
        group: "settings",
        key: "row-label-color",
        path: &["style", "settings", "row-label-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Row label color",
            default: "rgba(255, 255, 255, 0.78)",
        }),
        variable: "--settings-row-label-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Settings window",
        group: "settings",
        key: "row-value-color",
        path: &["style", "settings", "row-value-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Row value color",
            default: "rgba(255, 255, 255, 0.58)",
        }),
        variable: "--settings-row-value-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Settings window",
        group: "settings",
        key: "color-error",
        path: &["style", "settings", "color-error"],
        setting: Some(SettingUiSpec::Color {
            label: "Error color",
            default: "#f28b82",
        }),
        variable: "--settings-color-error",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Settings window",
        group: "settings",
        key: "token-background-color",
        path: &["style", "settings", "token-background-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Widget token background",
            default: "rgba(255, 255, 255, 0.1)",
        }),
        variable: "--settings-token-background-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Settings window",
        group: "settings",
        key: "token-drop-border-color",
        path: &["style", "settings", "token-drop-border-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Drop target border",
            default: "rgba(125, 200, 255, 0.95)",
        }),
        variable: "--settings-token-drop-border-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Settings window",
        group: "settings",
        key: "token-invalid-color",
        path: &["style", "settings", "token-invalid-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Invalid token color",
            default: "rgba(255, 180, 170, 1)",
        }),
        variable: "--settings-token-invalid-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Settings window",
        group: "settings",
        key: "token-invalid-border-color",
        path: &["style", "settings", "token-invalid-border-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Invalid token border",
            default: "rgba(255, 99, 71, 0.9)",
        }),
        variable: "--settings-token-invalid-border-color",
        css_kind: CssValueKind::String { quoted: false },
    },
    StyleSettingSpec {
        section: "Settings window",
        group: "settings",
        key: "token-drop-background-color",
        path: &["style", "settings", "token-drop-background-color"],
        setting: Some(SettingUiSpec::Color {
            label: "Drop target background",
            default: "rgba(125, 200, 255, 0.18)",
        }),
        variable: "--settings-token-drop-background-color",
        css_kind: CssValueKind::String { quoted: false },
    },
];
